---
# luks_drives describes a list of drives to be encrypted using LUKS
# Can be configured in the inventory file as well as in the group_vars or in the playbook
# mountpoint and fstype are optional fields
# Example:
# luks_drives:
#   - device: /dev/nvme1n1
#     keyfile: /etc/luks/nvme1n1.keyfile
#     name: nvme1n1
#     mountpoint: /mnt/luks
#     fstype: ext4
luks_drives: []
